### ISSUE TITLE
'®' character in service breaks yunohost service administration

### ISSUE THREAD

**Issue by artlog** [artlog/trivabble_ynh#1]
After install yunohost administration can't display services anymore :

Action
GET /services
{"locale":"en"}
Traceback
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/moulinette/interfaces/api.py", line 489, in process
    ret = self.actionsmap.process(arguments, timeout=30, route=_route)
  File "/usr/lib/python2.7/dist-packages/moulinette/actionsmap.py", line 588, in process
    return func(**arguments)
  File "/usr/lib/moulinette/yunohost/service.py", line 302, in service_status
    output = {s: _get_and_format_service_status(s, infos) for s, infos in services.items()}
  File "/usr/lib/moulinette/yunohost/service.py", line 302, in 
    output = {s: _get_and_format_service_status(s, infos) for s, infos in services.items()}
  File "/usr/lib/moulinette/yunohost/service.py", line 357, in _get_and_format_service_status
    try:
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xae' in position 18: ordinal not in range(128)

**Comment by artlog** [comment]
This is a yunohost problem , remove offending character to do it simple.
